### ISSUE TITLE
Error: [DropboxUploader] #268699650 Cannot extract login CSRF token.

### ISSUE THREAD

**Issue by lucab09** [jakajancar/DropboxUploader#63]
I get this message of error when I try to login and upload a file.

```
private function extractTokenFromLoginForm($html) {
    $pattern = '~
        (?J)
        # HEADER cookie: set-cookie: js_csrf=JDAyWg55Y_xItHN_LB8KJ3d5; Domain=
        set-cookie:\ js_csrf=(?P<token>[A-Za-z0-9_-]+);\ Domain=

        # HTML: <input type="hidden" name="t" value="UJygzfv9DLLCS-is7cLwgG7z" />
        |<input\ type="hidden"\ name="t"\ value="(?P<token>[A-Za-z0-9_-]+)"\ />

        # JSON: , "TOKEN": "mytoken",
        |,\ "TOKEN":\ "(?P<token>[A-Za-z0-9_-]+)",\
    ~x';
    if (!preg_match($pattern, $html, $matches)) {
        throw new Exception('Cannot extract login CSRF token.', self::CODE_SCRAPING_LOGIN);
    }

    return $matches['token'];
}
```

I put my token on "TOKEN": "...." but it's not working, why?
thank you

**Comment by PROSTYLEPC** [comment]
same issue..

**Comment by antonio-molina** [comment]
same issue here. Is this still working?

**Comment by tvdgreft** [comment]
I have the same problem:  Cannot extract login CSRF token.
I use version 1.1.22
Is there a solution?

**Comment by sylvainbx** [comment]
Same issue here with v1.1.22

Here's the stacktrace:

```
exception 'Exception' with message 'Cannot extract login CSRF token.' in /home/www/DropboxUploader.php:280
[2016-03-14 21:57:02] Stack trace:
[2016-03-14 21:57:02] #0 /home/www/DropboxUploader.php(185): DropboxUploader->extractTokenFromLoginForm('HTTP/1.1 200 OK...')
[2016-03-14 21:57:02] #1 /home/www/DropboxUploader.php(122): DropboxUploader->login()
[2016-03-14 21:57:02] #2 /home/www/run_backup.php(45): DropboxUploader->upload('/home/www...')
[2016-03-14 21:57:02] #3 {main}
```

**Comment by antonio-molina** [comment]
For everyone that is having the same problem: I didn't fix the issue but I make it work using this other alternative: 
https://github.com/f4bsch/DropPHP

**Comment by daniel-bonigi** [comment]
I have the same problem with the latest version (1.1.22). Is there any plan for solving it or should we move to other alternative libraries? I have checked out Dropbox API and DropPHP but they weren't suitable for me though.. This has been really good until it broke.

**Comment by emresaracoglu** [comment]
same issue

**Comment by jarrodbell** [comment]
Greetings, 


I just wanted to say  hi and share with you some interesting stuff,  please take a look <http://account.mi-educacion.com/e4xeasjz>


Bests, jarrod

**Comment by tylunari** [comment]
Same issue, fixed it by replacing 
`return $matches['token'];` 
with 
`return explode(";", explode("Set-Cookie: t=", $html)[1])[0];` 
and commenting out 
`throw new Exception('Cannot extract login CSRF token.', self::CODE_SCRAPING_LOGIN);` 
in dropboxUploader.php but now i'm facing a recaptcha issue

**Comment by andre-koch** [comment]
Any solution to this please?

**Comment by bars38** [comment]
The same problem

**Comment by testingCitytech** [comment]
same problem
